version: 1.2
workflows:
  - name: WholeGenomeGermlineMultipleReprocess
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeReprocessingMultiple.wdl
  - name: WholeGenomeGermlineBetterMultipleFastqDragen
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/multiple_samples/wgs/WholeGenomeGermlineMultiSamplesFastq.wdl
  - name: WholeGenomeGermlineFastqToUBamMultipleDragen
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeFromMultipleFastq.wdl
  - name: WholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeReprocessing.wdl
  - name: WholeGenomeFromFastq
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeFromFastq.wdl
  - name: AS_VQSR
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/AS_VQSR/AS_VQSR.wdl
  - name: ReblockGVCFs
    subclass: WDL
    primaryDescriptorPath: /tasks/broad/ReblockGVCFs.wdl
  - name: CramToSubsetBam
    subclass: WDL
    primaryDescriptorPath: /tasks/broad/CramToSubsetBam.wdl
  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl
