version: 1.2
workflows:
  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl
  - name: OptimusPostProcessing
    subclass: WDL
    primaryDescriptorPath: /projects/hca_mvp/OptimusPostProcessing.wdl
  - name: CEMBA
    subclass: WDL
    primaryDescriptorPath: /pipelines/cemba/cemba_methylcseq/CEMBA.wdl
