version: 1.2
workflows:
  - name: WholeGenomeGermlineMultipleReprocess
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeReprocessingMultiple.wdl
  - name: WholeGenomeGermlineBetterMultipleFastqDragen
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/multiple_samples/wgs/WholeGenomeGermlineMultiSamplesFastq.wdl
  - name: WholeGenomeGermlineFastqToUBamMultipleDragen
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeFromMultipleFastq.wdl
  - name: WholeGenomeReprocessing
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/reprocessing/wgs/WholeGenomeReprocessing.wdl
